"""Versioned artifact contracts and validation helpers."""

from kedit_audit.artifacts.hashing import (
    ArtifactHash,
    canonical_json_bytes,
    hash_bytes,
    hash_file,
    hash_json,
)
from kedit_audit.artifacts.io import (
    DEFAULT_MAX_JSON_BYTES,
    JsonInputError,
    load_json_document,
)
from kedit_audit.artifacts.schema import (
    AUDIT_CASE_SCHEMA_VERSION,
    AUDIT_REPORT_SCHEMA_VERSION,
    EDITOR_ARTIFACT_SCHEMA_VERSION,
    METRIC_RESULT_SCHEMA_VERSION,
    REPORT_COMPARISON_SCHEMA_VERSION,
    RIPPLE_CASE_SCHEMA_VERSION,
    RUN_MANIFEST_SCHEMA_VERSION,
    AuditCaseValidationError,
    AuditReportValidationError,
    EditorArtifactManifestValidationError,
    MetricResultValidationError,
    ReportComparisonValidationError,
    RippleCaseValidationError,
    RunManifestValidationError,
    ValidationIssue,
    load_audit_case_schema,
    load_audit_report_schema,
    load_editor_artifact_schema,
    load_metric_result_schema,
    load_report_comparison_schema,
    load_ripple_case_schema,
    load_run_manifest_schema,
    validate_audit_case,
    validate_audit_report,
    validate_editor_artifact_manifest,
    validate_metric_result,
    validate_report_comparison,
    validate_ripple_case,
    validate_run_manifest,
)
from kedit_audit.artifacts.writer import ArtifactWriteError, write_bytes_atomically

__all__ = [
    "AUDIT_CASE_SCHEMA_VERSION",
    "AUDIT_REPORT_SCHEMA_VERSION",
    "DEFAULT_MAX_JSON_BYTES",
    "EDITOR_ARTIFACT_SCHEMA_VERSION",
    "METRIC_RESULT_SCHEMA_VERSION",
    "REPORT_COMPARISON_SCHEMA_VERSION",
    "RIPPLE_CASE_SCHEMA_VERSION",
    "RUN_MANIFEST_SCHEMA_VERSION",
    "ArtifactHash",
    "ArtifactWriteError",
    "AuditCaseValidationError",
    "AuditReportValidationError",
    "EditorArtifactManifestValidationError",
    "JsonInputError",
    "MetricResultValidationError",
    "ReportComparisonValidationError",
    "RippleCaseValidationError",
    "RunManifestValidationError",
    "ValidationIssue",
    "canonical_json_bytes",
    "hash_bytes",
    "hash_file",
    "hash_json",
    "load_audit_case_schema",
    "load_audit_report_schema",
    "load_editor_artifact_schema",
    "load_json_document",
    "load_metric_result_schema",
    "load_report_comparison_schema",
    "load_ripple_case_schema",
    "load_run_manifest_schema",
    "validate_audit_case",
    "validate_audit_report",
    "validate_editor_artifact_manifest",
    "validate_metric_result",
    "validate_report_comparison",
    "validate_ripple_case",
    "validate_run_manifest",
    "write_bytes_atomically",
]
